apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: rabbitmq-operator
spec:
  interval: 5m0s
  url: https://github.com/loicalbertin/flux-karmada-rabbitmq-operator
  ref:
    branch: "main"

---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rabbitmq-operator
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: rabbitmq-operator
  path: ./deploy/manifests/operator
  prune: true

---

apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: rabbitmq-op-policy
spec:
  propagateDeps: true
  resourceSelectors:
    - apiVersion: source.toolkit.fluxcd.io/v1beta2
      kind: GitRepository
      name: rabbitmq-operator
    - apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      name: rabbitmq-operator
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member3